--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# domain to which this site is deployed
base_url: http://schmurfy.github.com

# google_analytics:
#   domain: mgutz.com
#   site_id: UA-9655468-1 

# number of full featured posts to display on front
featured_count: 0

# number of other articles to reference at bottom of each article
other_articles_max: 3

# DISQUS Site Shortname. Comment out to disable.
# disqus_shortname: nanoc3-blog

